[package]
name = "ballroom-ensemble"
version = "0.1.0"
edition = "2024"

[lib]
name = "ballroom_ensemble"
path = "src/lib.rs"

[[bin]]
name = "ballroom"
path = "src/bin/main.rs"

[dependencies]
eframe = { version = "0.33.3", features = ["persistence", "accesskit", "serde"] }
egui = { version = "0.33.3", features = ["accesskit", "persistence", "rayon"] }
egui_tiles = { version = "0.14.1", features = ["serde"] }
clap = { version = "4.5.54", features = ["derive", "cargo", "env", "string", "unicode", "wrap_help"] }
crossbeam-channel = { version = "0.5.15" }
rfd = { version = "0.17.2" }
directories = { version = "6.0.0" }
chrono = { version = "0.4.43", features = ["serde", "now"] }

sha2 = { version = "0.11.0-rc.5" }
serde = { version = "1.0.228", features = ["derive", "alloc", "rc"] }
toml = { version = "0.9.11", features = ["fast_hash"] }

lockstep-ensemble = { path = "../core" }
