[package]
name = "ensemble-ballroom"
version = "0.1.0"
edition = "2024"

[lib]
name = "ensemble_ballroom"
path = "src/lib.rs"

[[bin]]
name = "ballroom"
path = "src/bin/main.rs"

[dependencies]
eframe = { version = "0.33.3", features = ["wgpu", "persistence"] }
egui = { version = "0.33.3", features = ["accesskit", "persistence", "rayon"] }
egui_tiles = { version = "0.14.1", features = ["serde"] }
clap = { version = "4.5.54", features = ["derive", "cargo", "env", "string", "unicode", "wrap_help"] }
crossbeam-channel = { version = "0.5.15" }
rfd = { version = "0.17.2" }
directories = { version = "6.0.0" }
chrono = { version = "0.4.43", features = ["serde", "now"] }
sha2 = { version = "0.11.0-rc.5" }
serde = { version = "1.0.228", features = ["derive", "alloc", "rc"] }
toml = { version = "1.0.2", features = ["fast_hash"] }

ensemble-lockstep = { path = "../core" }
ensemble-gown = { path = "../renderer", optional = true }
tokio = { version = "1.49.0", features = ["rt"] }

[features]
default = ["default_renderers"]
default_renderers = ["ensemble-gown"]

# Web-only dependencies
[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = { version = "0.3", features = ["Window", "Document", "HtmlCanvasElement"] }
wasm-bindgen = "0.2.108"
wasm-bindgen-futures = "0.4.58"