[workspace]
members = ["core"]
default-members = ["core"]
resolver = "2"

[profile.release]
strip = "symbols"
#lto = true
#codegen-units = 1

[profile.profiling]
inherits = "release"
strip = "none"
debug = "full"
split-debuginfo = "unpacked"  # Ensures symbols are separate
