[workspace]
members = [
    "core",
    "ffi",
]
default-members = ["core"]
resolver = "2"

[profile.profiling]
inherits = "release"
debug = true
split-debuginfo = "unpacked"  # Ensures symbols are separate