[workspace]
members = [
    "core",
]
default-members = ["core"]
resolver = "2"

[patch.crates-io]
imgui-sdl3 = { path = "vendor/imgui-sdl3" }

[profile.profiling]
inherits = "release"
lto = false
codegen-units = 1
debug = true
split-debuginfo = "unpacked"  # Ensures symbols are separate