[package]
name = "nesamabob"
version = "0.1.0"
edition = "2024"

[profile.dev]
opt-level = 0         # Or 2 if you want more speed
debug = true           # Keep debug info for debugging
lto = false            # LTO slows compilation a lot
codegen-units = 1    # Keeps compile times reasonable
overflow-checks = false

[profile.dev.package."*"]
opt-level = 3          # Force hot inner loops in dependencies to be fast

[profile.test]
opt-level = 0         # Or 2 if you want more speed
debug = true           # Keep debug info for debugging
lto = false            # LTO slows compilation a lot
codegen-units = 1    # Keeps compile times reasonable

[profile.profiling]
inherits = "release"
debug = true
split-debuginfo = "unpacked"  # Ensures symbols are separate

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = { version = "2", features = ["serde"] }
sdl2 = "0.38.0"
bytemuck = "1.23.2"