condense_wildcard_suffixes = true
fn_single_line = true
hex_literal_case = 'Upper'
imports_granularity = 'Module'
newline_style = 'Unix'
normalize_doc_attributes = true
reorder_impl_items = true
group_imports = 'StdExternalCrate'
format_code_in_doc_comments = true
struct_lit_single_line = false
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true