[package]
name = "ensemble-choreo"
version = "0.1.0"
edition = "2024"

[lib]
name = "ensemble_choreo"
path = "src/lib.rs"

[[bin]]
name = "choreo"
path = "src/bin/main.rs"

[dependencies]
serde = {version = "1.0.228", features = ["derive", "alloc", "rc"]}
serde_json = { version = "1.0.149" }
postcard = {version = "1.1.3", features = ["use-std"]}
clap = { version = "4.5.54", features = ["derive", "cargo", "env", "string", "unicode", "wrap_help"] }
toml = {version = "1.0.2", features = ["fast_hash"]}
image = {version = "0.25.9"}

ensemble-lockstep = { path = "../core" }

