[package]
name = "nes_core"
version = "0.1.0"
edition = "2024"

[lib]
name = "nes_core"
path = "src/lib.rs"

[[bin]]
name = "nes_main"
path = "src/bin/main.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = { version = "2.0.1", features = ["serde"] }
sdl2 = { version = "0.37.0", optional = true, features = ["gfx"] }
bytemuck = "1.23.2"
imgui = { version = "0.12.0", optional = true }
imgui-sdl2-support = { version = "0.13.0", optional = true }
imgui-glow-renderer = { version = "0.13.0", optional = true }
glow = { version = "0.14", optional = true }
crossbeam-channel = "0.5.15"
eframe = { version = "0.31", optional = true }
egui = { version = "0.31", optional = true }
egui_extras = { version = "0.31", optional = true, features = ["image"] }

[features]
default = []
sdl2-frontend = ["sdl2"]
imgui-frontend = ["sdl2", "imgui", "imgui-sdl2-support", "imgui-glow-renderer", "glow"]
egui-frontend = ["eframe", "egui", "egui_extras"]
