[package]
name = "nes_core"
version = "0.1.0"
edition = "2024"

[lib]
name = "nes_core"
path = "src/lib.rs"

[[bin]]
name = "nes_main"
path = "src/bin/main.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = { version = "1.3" }
crossbeam-channel = { version = "0.5.15" }
rfd = { version = "0.17.2" }
eframe = { version = "0.33.3", features = ["persistence", "accesskit", "serde"] }
egui = { version = "0.33.3", features = ["accesskit", "persistence", "rayon"] }
egui_tiles = { version = "0.14.1", features = ["serde"] }
egui_hotkey = { version = "0.2.0", features = ["serde"] }
egui_double_slider = { version = "1.0.0" }
clap = { version = "4.5.54", features = ["derive", "cargo", "env", "string", "unicode", "wrap_help"] }
sha2 = { version = "0.11.0-rc.4" }
cpal = { version = "0.17.1" }
directories = { version = "6.0.0" }
toml = { version = "0.9.11" }