[package]
name = "nes_core"
version = "0.1.0"
edition = "2024"

[lib]
name = "nes_core"
path = "src/lib.rs"

[[bin]]
name = "nes_main"
path = "src/bin/main.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = { version = "2", features = ["serde"] }
sdl3 = { version = "0.16.1", optional = true, features = ["build-from-source"] }
bytemuck = "1.24"
imgui = { version = "0.12.0", optional = true }
imgui-sdl3 = { version = "0.4.1", optional = true }
crossbeam-channel = "0.5.15"

[features]
default = []
frontend = ["imgui", "sdl3", "imgui-sdl3"]
