[package]
name = "nes_core"
version = "0.1.0"
edition = "2024"

[lib]
name = "nes_core"
path = "src/lib.rs"

[[bin]]
name = "nes_main"
path = "src/bin/main.rs"

[dependencies]
rkyv = { version = "0.8.14", features = ["std", "bytecheck"] }
crossbeam-channel = "0.5.15"
rfd = { version = "0.17.2" }
eframe = { version = "0.33.3" }
egui = { version = "0.33.3" }
egui_tiles = { version = "0.14.1" }
clap = { version = "4.5.54", features = ["derive"] }