[package]
name = "nes_core"
version = "0.1.0"
edition = "2024"

[lib]
name = "nes_core"
path = "src/lib.rs"

[[bin]]
name = "nes_main"
path = "src/bin/main.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = { version = "2", features = ["serde"] }
sdl2 = { version = "0.38.0", optional = true }
bytemuck = "1.23.2"
sdl3 = { version = "0.16.1", optional = true, features = ["build-from-source"] }
imgui = { version = "0.12.0", optional = true }
imgui-sdl3 = { version = "0.4.1", optional = true }
log = "0.4.28"
crossbeam-channel = "0.5.15"

[features]
default = []
sdl2-frontend = ["sdl2"]
imgui-frontend = ["sdl3", "imgui", "sdl2", "imgui-sdl3"]
