[package]
name = "nes_core"
version = "0.1.0"
edition = "2024"

[lib]
name = "nes_core"
path = "src/lib.rs"

[[bin]]
name = "nes_main"
path = "src/bin/main.rs"

[dependencies]
rkyv = { version = "0.8.13", features = ["std", "bytecheck"] }
sdl2 = { version = "0.37.0", optional = true, features = ["gfx"] }
bytemuck = "1.23.2"
crossbeam-channel = "0.5.15"
eframe = { version = "0.33.3", optional = true }
egui = { version = "0.33.3", optional = true, features = ["bytemuck"] }
egui_extras = { version = "0.33.3", optional = true, features = ["image"] }

[features]
default = []
sdl2-frontend = ["sdl2"]
egui-frontend = ["eframe", "egui", "egui_extras"]
