[package]
name = "nes_core"
version = "0.1.0"
edition = "2024"

[lib]
name = "nes_core"
path = "src/lib.rs"

[[bin]]
name = "nes_main"
path = "src/bin/main.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = { version = "2", features = ["serde"] }
sdl2 = { version = "0.38.0", optional = true }
sdl3 = { version = "0.5", optional = true }
imgui = { version = "0.12", optional = true }
imgui-opengl-renderer = { version = "0.12", optional = true }
glow = { version = "0.13", optional = true }
bytemuck = "1.23.2"
log = "0.4.28"

[features]
default = []
sdl2-frontend = ["sdl2"]
imgui-sdl3-frontend = ["sdl3", "imgui", "imgui-opengl-renderer", "glow"]
