[package]
name = "nes_core"
version = "0.1.0"
edition = "2024"

[lib]
name = "nes_core"
path = "src/lib.rs"

[[bin]]
name = "nes_main"
path = "src/bin/main.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = { version = "2.0.1", features = ["serde"] }
crossbeam-channel = "0.5.15"

eframe = { version = "0.33.3" }
egui = { version = "0.33.3", features = ["bytemuck", "serde"] }
egui_extras = { version = "0.33.3", features = ["image", "serde"] }
clap = { version = "4.5.54", features = ["derive"] }
