[package]
name = "nes_core"
version = "0.1.0"
edition = "2024"

[lib]
name = "nes_core"
path = "src/lib.rs"

[[bin]]
name = "nes_main"
path = "src/bin/main.rs"

[dependencies]
rkyv = { version = "0.8.14", features = ["std", "bytecheck"] }
crossbeam-channel = { version = "0.5.15" }
rfd = { version = "0.17.2" }
eframe = { version = "0.33.3" }
egui = { version = "0.33.3" }
egui_tiles = { version = "0.14.1" }
clap = { version = "4.5.54", features = ["derive"] }
sha2 = { version = "0.11.0-rc.4" }
toml = {version = "0.9.11+spec-1.1.0"}
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0.149" }